name: Build, Test and Deploy React Application

# Controls when the action will run
on: 
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in 
jobs:
  build_test:
    permissions: # job-level permissions configuration start here
      contents: write # write acces to repository contents
      pull-requests: write # write access to pull request
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-versions: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci
          npm test
      - name: Versioning build
        run: |
          git config --global user.email "cecile.niess@ynov.com"
          git config --global user.name "cecile"
          git tag v0.1.1-${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}} -a -m "buil version ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
          npm version from-git --allow-same-version
          echo ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}} >> README.md
          git add .
          git commit -am "update versioning"
          git push
      - name: Build dans docs 
        run: |
          npm run jsdoc
          npm run build --if-present
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Download artifact
      - name: Upload entire repository
        uses: actions/upload-pages-artifact@v4
        with:
        #Upload entire repository
          path: |
            build
            artifact
          if-no-files-found: error
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
      
  #Deploy job
  deploy:
    #Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    #Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write #to deploy to Pages
      id-token: write #to verify the deployment originales from an appropriate source
    #Add a dependency to build job
    needs: build_test
    #Specify runner + deployement step
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
